import type { WallpaperConfig } from '@wallpaper-maker/core';

// Touches config fields so deep in-place mutations are observed by Svelte runes.
export function touchPreviewDeps(config: WallpaperConfig, renderMode: unknown, exportFormat: unknown): void {
  const c = config as any;
  void c.type;
  void c.width;
  void c.height;
  void c.seed;
  void c.colors.join(',');
  {
    const ovs: any[] | undefined = c.palette?.overrides;
    if (Array.isArray(ovs)) {
      for (const o of ovs) {
        if (!o || typeof o !== 'object') continue;
        void o.enabled;
        void o.emission?.enabled;
        void o.emission?.intensity;
        void o.texture?.type;
        void o.texture?.params?.drywall?.grainAmount;
        void o.texture?.params?.drywall?.grainScale;
        void o.texture?.params?.glass?.style;
        void o.texture?.params?.cel?.bands;
        void o.texture?.params?.cel?.halftone;
        void o.facades?.grazing?.enabled;
        void o.facades?.grazing?.mode;
        void o.facades?.grazing?.color;
        void o.facades?.grazing?.strength;
        void o.facades?.grazing?.power;
        void o.facades?.grazing?.width;
        void o.facades?.grazing?.noise;
        void o.facades?.side?.enabled;
        void o.facades?.side?.tintColor;
        void o.facades?.side?.tintAmount;
        void o.facades?.side?.materialAmount;
        void o.facades?.side?.roughness;
        void o.facades?.side?.metalness;
        void o.facades?.side?.clearcoat;
        void o.facades?.side?.envIntensityMult;
        void o.facades?.outline?.enabled;
        void o.facades?.outline?.color;
        void o.facades?.outline?.thickness;
        void o.facades?.outline?.opacity;
        void o.edge?.hollow;
        void o.edge?.seam?.enabled;
        void o.edge?.seam?.color;
        void o.edge?.seam?.opacity;
        void o.edge?.seam?.width;
        void o.edge?.seam?.noise;
        void o.edge?.seam?.emissiveIntensity;
        void o.edge?.band?.enabled;
        void o.edge?.band?.color;
        void o.edge?.band?.opacity;
        void o.edge?.band?.width;
        void o.edge?.band?.noise;
        void o.edge?.band?.emissiveIntensity;
        void o.voronoi?.enabled;
        void o.voronoi?.space;
        void o.voronoi?.kind;
        void o.voronoi?.scale;
        void o.voronoi?.seedOffset;
        void o.voronoi?.amount;
        void o.voronoi?.edgeWidth;
        void o.voronoi?.softness;
        void o.voronoi?.colorStrength;
        void o.voronoi?.colorMode;
        void o.voronoi?.tintColor;
        void o.voronoi?.materialMode;
        void (o.voronoi as any)?.materialKind;
        void o.voronoi?.roughnessStrength;
        void o.voronoi?.normalStrength;
        void o.voronoi?.normalScale;
        void (o.voronoi as any)?.crackleAmount;
        void (o.voronoi as any)?.crackleScale;
        void (o.voronoi as any)?.nucleus?.enabled;
        void (o.voronoi as any)?.nucleus?.size;
        void (o.voronoi as any)?.nucleus?.softness;
        void (o.voronoi as any)?.nucleus?.strength;
        void (o.voronoi as any)?.nucleus?.color;
      }
    }
  }
  void c.texture;
  void c.textureParams?.drywall?.grainAmount;
  void c.textureParams?.drywall?.grainScale;
  void c.textureParams?.glass?.style;
  void c.textureParams?.cel?.bands;
  void c.textureParams?.cel?.halftone;
  void c.voronoi?.enabled;
  void c.voronoi?.space;
  void c.voronoi?.kind;
  void c.voronoi?.scale;
  void c.voronoi?.seedOffset;
  void c.voronoi?.amount;
  void c.voronoi?.edgeWidth;
  void c.voronoi?.softness;
  void c.voronoi?.colorStrength;
  void c.voronoi?.colorMode;
  void c.voronoi?.tintColor;
  void c.voronoi?.materialMode;
  void c.voronoi?.materialKind;
  void c.voronoi?.roughnessStrength;
  void c.voronoi?.normalStrength;
  void c.voronoi?.normalScale;
  void c.voronoi?.crackleAmount;
  void c.voronoi?.crackleScale;
  void c.voronoi?.nucleus?.enabled;
  void c.voronoi?.nucleus?.size;
  void c.voronoi?.nucleus?.softness;
  void c.voronoi?.nucleus?.strength;
  void c.voronoi?.nucleus?.color;
  void c.backgroundColor;
  void c.facades?.side?.enabled;
  void c.facades?.side?.tintColor;
  void c.facades?.side?.tintAmount;
  void c.facades?.side?.materialAmount;
  void c.facades?.side?.roughness;
  void c.facades?.side?.metalness;
  void c.facades?.side?.clearcoat;
  void c.facades?.side?.envIntensityMult;
  void c.facades?.grazing?.enabled;
  void c.facades?.grazing?.mode;
  void c.facades?.grazing?.color;
  void c.facades?.grazing?.strength;
  void c.facades?.grazing?.power;
  void c.facades?.grazing?.width;
  void c.facades?.grazing?.noise;
  void c.facades?.outline?.enabled;
  void c.facades?.outline?.color;
  void c.facades?.outline?.thickness;
  void c.facades?.outline?.opacity;
  void c.edge?.hollow;
  void c.edge?.seam?.enabled;
  void c.edge?.seam?.color;
  void c.edge?.seam?.opacity;
  void c.edge?.seam?.width;
  void c.edge?.seam?.noise;
  void c.edge?.seam?.emissiveIntensity;
  void c.edge?.band?.enabled;
  void c.edge?.band?.color;
  void c.edge?.band?.opacity;
  void c.edge?.band?.width;
  void c.edge?.band?.noise;
  void c.edge?.band?.emissiveIntensity;
  void c.emission?.enabled;
  void c.emission?.paletteIndex;
  void c.emission?.intensity;
  void c.bloom?.enabled;
  void c.bloom?.strength;
  void c.bloom?.radius;
  void c.bloom?.threshold;
  void c.collisions?.mode;
  void c.collisions?.carve?.direction;
  void c.collisions?.carve?.marginPx;
  void c.collisions?.carve?.edge;
  void c.collisions?.carve?.featherPx;
  void c.bubbles?.enabled;
  void c.bubbles?.frequency;
  void c.bubbles?.frequencyVariance;
  void c.bubbles?.count;
  void c.bubbles?.mode;
  void c.bubbles?.radiusMin;
  void c.bubbles?.radiusMax;
  void c.bubbles?.softness;
  void c.bubbles?.wallThickness;
  void c.bubbles?.seedOffset;
  void c.bubbles?.interior?.enabled;

  if (c.type === 'popsicle') {
    void c.stickCount;
    void c.stickOverhang;
    void c.rotationCenterOffsetX;
    void c.rotationCenterOffsetY;
    void c.stickGap;
    void c.stickSize;
    void c.stickRatio;
    void c.stickThickness;
    void c.stickEndProfile;
    void c.stickRoundness;
    void c.stickChipAmount;
    void c.stickChipJaggedness;
    void c.stickBevel;
    void c.stickOpacity;
  }
  if (c.type === 'spheres3d') {
    void c.spheres?.count;
    void c.spheres?.distribution;
    void c.spheres?.radiusMin;
    void c.spheres?.radiusMax;
    void c.spheres?.spread;
    void c.spheres?.depth;
    void c.spheres?.layers;
    void c.spheres?.paletteMode;
    void c.spheres?.colorWeights?.join(',');
    void c.spheres?.opacity;
    void c.spheres?.shape?.kind;
    void c.spheres?.shape?.roundness;
    void c.spheres?.shape?.faceting;
  }
  if (c.type === 'bands2d') {
    void c.bands?.mode;
    void c.bands?.seedOffset;
    void c.bands?.angleDeg;
    void c.bands?.bandWidthPx;
    void c.bands?.gapPx;
    void c.bands?.offsetPx;
    void c.bands?.jitterPx;
    void c.bands?.fill?.enabled;
    void c.bands?.fill?.opacity;
    void c.bands?.stroke?.enabled;
    void c.bands?.stroke?.widthPx;
    void c.bands?.stroke?.color;
    void c.bands?.stroke?.opacity;
    void c.bands?.waves?.amplitudePx;
    void c.bands?.waves?.wavelengthPx;
    void c.bands?.waves?.noiseAmount;
    void c.bands?.waves?.noiseScale;
    void c.bands?.chevron?.amplitudePx;
    void c.bands?.chevron?.wavelengthPx;
    void c.bands?.chevron?.sharpness;
    void c.bands?.chevron?.sharedPhase;
    void c.bands?.paletteMode;
    void c.bands?.colorWeights?.join(',');
  }
  if (c.type === 'flowlines2d') {
    void c.flowlines?.seedOffset;
    void c.flowlines?.frequency;
    void c.flowlines?.octaves;
    void c.flowlines?.warpAmount;
    void c.flowlines?.warpFrequency;
    void c.flowlines?.strength;
    void c.flowlines?.epsilonPx;
    void c.flowlines?.spawn;
    void c.flowlines?.density;
    void c.flowlines?.spacingPx;
    void c.flowlines?.marginPx;
    void c.flowlines?.stepPx;
    void c.flowlines?.maxSteps;
    void c.flowlines?.maxLines;
    void c.flowlines?.minLengthPx;
    void c.flowlines?.jitter;
    void c.flowlines?.stroke?.widthPx;
    void c.flowlines?.stroke?.opacity;
    void c.flowlines?.stroke?.taper;
    void c.flowlines?.paletteMode;
    void c.flowlines?.colorWeights?.join(',');
    void c.flowlines?.colorJitter;
  }
  if (c.type === 'diamondgrid2d') {
    void c.diamondgrid?.tileWidthPx;
    void c.diamondgrid?.tileHeightPx;
    void c.diamondgrid?.marginPx;
    void c.diamondgrid?.sizeVariance;
    void c.diamondgrid?.originPx?.x;
    void c.diamondgrid?.originPx?.y;
    void c.diamondgrid?.overscanPx;
    void c.diamondgrid?.panel?.enabled;
    void c.diamondgrid?.panel?.rectFrac?.x;
    void c.diamondgrid?.panel?.rectFrac?.y;
    void c.diamondgrid?.panel?.rectFrac?.w;
    void c.diamondgrid?.panel?.rectFrac?.h;
    void c.diamondgrid?.fillOpacity;
    void c.diamondgrid?.stroke?.enabled;
    void c.diamondgrid?.stroke?.widthPx;
    void c.diamondgrid?.stroke?.color;
    void c.diamondgrid?.stroke?.opacity;
    void c.diamondgrid?.stroke?.join;
    void c.diamondgrid?.coloring?.paletteMode;
    void c.diamondgrid?.coloring?.colorWeights?.join(',');
    void c.diamondgrid?.bevel?.enabled;
    void c.diamondgrid?.bevel?.amount;
    void c.diamondgrid?.bevel?.mode;
    void c.diamondgrid?.bevel?.lightDeg;
    void c.diamondgrid?.bevel?.variation;
  }
  if (c.type === 'circles2d') {
    void c.circles?.mode;
    void c.circles?.count;
    void c.circles?.rMinPx;
    void c.circles?.rMaxPx;
    void c.circles?.jitter;
    void c.circles?.fillOpacity;
    void c.circles?.stroke?.enabled;
    void c.circles?.stroke?.widthPx;
    void c.circles?.stroke?.color;
    void c.circles?.stroke?.opacity;
    void c.circles?.paletteMode;
    void c.circles?.colorWeights?.join(',');
    void c.circles?.croissant?.enabled;
    void c.circles?.croissant?.innerScale;
    void c.circles?.croissant?.offset;
    void c.circles?.croissant?.angleJitterDeg;
  }
  if (c.type === 'polygon2d') {
    void c.polygons?.mode;
    void c.polygons?.shape;
    void c.polygons?.count;
    void c.polygons?.edges;
    void c.polygons?.rMinPx;
    void c.polygons?.rMaxPx;
    void c.polygons?.jitter;
    void c.polygons?.rotateJitterDeg;
    void c.polygons?.grid?.kind;
    void c.polygons?.grid?.cellPx;
    void c.polygons?.grid?.jitter;
    void c.polygons?.star?.innerScale;
    void c.polygons?.fillOpacity;
    void c.polygons?.stroke?.enabled;
    void c.polygons?.stroke?.widthPx;
    void c.polygons?.stroke?.color;
    void c.polygons?.stroke?.opacity;
    void c.polygons?.paletteMode;
    void c.polygons?.colorWeights?.join(',');
  }
  if (c.type === 'triangles2d') {
    void c.triangles?.mode;
    void c.triangles?.density;
    void c.triangles?.scalePx;
    void c.triangles?.jitter;
    void c.triangles?.rotateJitterDeg;
    void c.triangles?.insetPx;
    void c.triangles?.fillOpacity;
    void c.triangles?.stroke?.enabled;
    void c.triangles?.stroke?.widthPx;
    void c.triangles?.stroke?.color;
    void c.triangles?.stroke?.opacity;
    void c.triangles?.paletteMode;
    void c.triangles?.colorWeights?.join(',');
    void c.triangles?.shading?.enabled;
    void c.triangles?.shading?.lightDeg;
    void c.triangles?.shading?.strength;
  }
  if (c.type === 'triangles3d') {
    void c.prisms?.mode;
    void c.prisms?.count;
    void c.prisms?.base;
    void c.prisms?.radius;
    void c.prisms?.height;
    void c.prisms?.taper;
    void c.prisms?.wallBulgeX;
    void c.prisms?.wallBulgeY;
    void c.prisms?.spread;
    void c.prisms?.jitter;
    void c.prisms?.paletteMode;
    void c.prisms?.colorWeights?.join(',');
    void c.prisms?.opacity;
  }
  if (c.type === 'svg2d') {
    void c.svg?.source;
    void c.svg?.renderMode;
    void c.svg?.colorMode;
    void c.svg?.maxTones;
    void c.svg?.count;
    void c.svg?.rMinPx;
    void c.svg?.rMaxPx;
    void c.svg?.jitter;
    void c.svg?.rotateJitterDeg;
    void c.svg?.fillOpacity;
    void c.svg?.stroke?.enabled;
    void c.svg?.stroke?.widthPx;
    void c.svg?.stroke?.color;
    void c.svg?.stroke?.opacity;
    void c.svg?.paletteMode;
    void c.svg?.colorWeights?.join(',');
  }
  if (c.type === 'svg3d') {
    void c.svg?.source;
    void c.svg?.renderMode;
    void c.svg?.colorMode;
    void c.svg?.maxTones;
    void c.svg?.count;
    void c.svg?.spread;
    void c.svg?.depth;
    void c.svg?.sizeMin;
    void c.svg?.sizeMax;
    void c.svg?.extrudeDepth;
    void c.svg?.stroke?.enabled;
    void c.svg?.stroke?.radius;
    void c.svg?.stroke?.segments;
    void c.svg?.stroke?.opacity;
    void c.svg?.bevel?.enabled;
    void c.svg?.bevel?.size;
    void c.svg?.bevel?.segments;
    void c.svg?.paletteMode;
    void c.svg?.colorWeights?.join(',');
    void c.svg?.opacity;
  }
  if (c.type === 'hexgrid2d') {
    void c.hexgrid?.radiusPx;
    void c.hexgrid?.marginPx;
    void c.hexgrid?.overscanPx;
    void c.hexgrid?.fillOpacity;
    void c.hexgrid?.originPx?.x;
    void c.hexgrid?.originPx?.y;
    void c.hexgrid?.stroke?.enabled;
    void c.hexgrid?.stroke?.widthPx;
    void c.hexgrid?.stroke?.join;
    void c.hexgrid?.stroke?.color;
    void c.hexgrid?.stroke?.opacity;
    void c.hexgrid?.coloring?.paletteMode;
    void c.hexgrid?.coloring?.weightsMode;
    void c.hexgrid?.coloring?.preset;
    void c.hexgrid?.coloring?.weights?.join(',');
    void c.hexgrid?.grouping?.mode;
    void c.hexgrid?.grouping?.strength;
    void c.hexgrid?.grouping?.targetGroupCount;
    void c.hexgrid?.effect?.kind;
    void c.hexgrid?.effect?.amount;
    void c.hexgrid?.effect?.frequency;
  }

  void c.camera?.distance;
  void c.camera?.azimuth;
  void c.camera?.elevation;
  void c.lighting?.enabled;
  void c.lighting?.intensity;
  void c.lighting?.position?.x;
  void c.lighting?.position?.y;
  void c.lighting?.position?.z;
  void c.lighting?.ambientIntensity;
  void c.environment?.enabled;
  void c.environment?.style;
  void c.environment?.intensity;
  void c.environment?.rotation;
  void c.shadows?.enabled;
  void c.shadows?.type;
  void c.shadows?.mapSize;
  void c.shadows?.bias;
  void c.shadows?.normalBias;
  void c.rendering?.toneMapping;
  void c.rendering?.exposure;
  void c.geometry?.quality;
  void renderMode;
  void exportFormat;
}
